
const content = {
  information: {
    address: {
      link: "https://www.google.co.uk/maps/",
      text: "Address"
    },
    email: {
      link: "mailto:mail@gmail.com",
      text: "mail@gmail.com"
    },
    phone: {
      link: "tel:000000000",
      text: "000000000"
    }
  },
  header: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum magna libero, sit amet pharetra felis porttitor eu. Etiam et augue quis leo imperdiet varius nec ut dui. Fusce nec metus mi. In ac lobortis dui, eget fringilla elit. Fusce neque erat, posuere vel nulla ut, auctor ultricies purus. Aliquam placerat nec turpis non porttitor. In et ullamcorper sem. Ut vestibulum vestibulum neque, congue volutpat sapien. Ut condimentum sodales arcu, eget dignissim lorem efficitur eget. Phasellus aliquet velit nec lorem maximus elementum. Quisque sit amet orci massa.",
  ivanti:[
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum magna libero, sit amet pharetra felis porttitor eu. Etiam et augue quis leo imperdiet varius nec ut dui. Fusce nec metus mi. In ac lobortis dui, eget fringilla elit. Fusce neque erat, posuere vel nulla ut, auctor ultricies purus. Aliquam placerat nec turpis non porttitor. In et ullamcorper sem. Ut vestibulum vestibulum neque, congue volutpat sapien. Ut condimentum sodales arcu, eget dignissim lorem efficitur eget. Phasellus aliquet velit nec lorem maximus elementum. Quisque sit amet orci massa.",
    "Nunc et elit varius, fermentum sapien eu, dignissim lacus. Vestibulum condimentum turpis ac ligula porttitor fringilla. Ut libero eros, egestas sed ex vel, viverra egestas augue. Phasellus lorem nisi, commodo id elementum aliquet, blandit ac leo. Quisque gravida, libero vel iaculis tempus, ligula nisi imperdiet velit, vel lobortis magna nibh sed mauris. Curabitur efficitur arcu sapien, non dapibus ipsum blandit commodo. Donec mollis dolor a augue lacinia, eget gravida sem placerat. Nullam ultrices in justo a pellentesque. Nam quis placerat ipsum. Integer convallis varius sapien, a ullamcorper metus sodales et. Aliquam erat volutpat. Praesent blandit, tellus sed consectetur gravida, nisi nisl interdum nulla, vel imperdiet lacus elit et elit. Nulla viverra tempus sapien, et eleifend justo vulputate id.",

  ],
  nicepak: [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum magna libero, sit amet pharetra felis porttitor eu. Etiam et augue quis leo imperdiet varius nec ut dui. Fusce nec metus mi. In ac lobortis dui, eget fringilla elit. Fusce neque erat, posuere vel nulla ut, auctor ultricies purus. Aliquam placerat nec turpis non porttitor. In et ullamcorper sem. Ut vestibulum vestibulum neque, congue volutpat sapien. Ut condimentum sodales arcu, eget dignissim lorem efficitur eget. Phasellus aliquet velit nec lorem maximus elementum. Quisque sit amet orci massa.",
    "Nunc et elit varius, fermentum sapien eu, dignissim lacus. Vestibulum condimentum turpis ac ligula porttitor fringilla. Ut libero eros, egestas sed ex vel, viverra egestas augue. Phasellus lorem nisi, commodo id elementum aliquet, blandit ac leo. Quisque gravida, libero vel iaculis tempus, ligula nisi imperdiet velit, vel lobortis magna nibh sed mauris. Curabitur efficitur arcu sapien, non dapibus ipsum blandit commodo. Donec mollis dolor a augue lacinia, eget gravida sem placerat. Nullam ultrices in justo a pellentesque. Nam quis placerat ipsum. Integer convallis varius sapien, a ullamcorper metus sodales et. Aliquam erat volutpat. Praesent blandit, tellus sed consectetur gravida, nisi nisl interdum nulla, vel imperdiet lacus elit et elit. Nulla viverra tempus sapien, et eleifend justo vulputate id.",
  ],
  redrow: [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum magna libero, sit amet pharetra felis porttitor eu. Etiam et augue quis leo imperdiet varius nec ut dui. Fusce nec metus mi. In ac lobortis dui, eget fringilla elit. Fusce neque erat, posuere vel nulla ut, auctor ultricies purus. Aliquam placerat nec turpis non porttitor. In et ullamcorper sem. Ut vestibulum vestibulum neque, congue volutpat sapien. Ut condimentum sodales arcu, eget dignissim lorem efficitur eget. Phasellus aliquet velit nec lorem maximus elementum. Quisque sit amet orci massa.",
    "Nunc et elit varius, fermentum sapien eu, dignissim lacus. Vestibulum condimentum turpis ac ligula porttitor fringilla. Ut libero eros, egestas sed ex vel, viverra egestas augue. Phasellus lorem nisi, commodo id elementum aliquet, blandit ac leo. Quisque gravida, libero vel iaculis tempus, ligula nisi imperdiet velit, vel lobortis magna nibh sed mauris. Curabitur efficitur arcu sapien, non dapibus ipsum blandit commodo. Donec mollis dolor a augue lacinia, eget gravida sem placerat. Nullam ultrices in justo a pellentesque. Nam quis placerat ipsum. Integer convallis varius sapien, a ullamcorper metus sodales et. Aliquam erat volutpat. Praesent blandit, tellus sed consectetur gravida, nisi nisl interdum nulla, vel imperdiet lacus elit et elit. Nulla viverra tempus sapien, et eleifend justo vulputate id.",
  ],
  sts: [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum magna libero, sit amet pharetra felis porttitor eu. Etiam et augue quis leo imperdiet varius nec ut dui. Fusce nec metus mi. In ac lobortis dui, eget fringilla elit. Fusce neque erat, posuere vel nulla ut, auctor ultricies purus. Aliquam placerat nec turpis non porttitor. In et ullamcorper sem. Ut vestibulum vestibulum neque, congue volutpat sapien. Ut condimentum sodales arcu, eget dignissim lorem efficitur eget. Phasellus aliquet velit nec lorem maximus elementum. Quisque sit amet orci massa.",
    "Nunc et elit varius, fermentum sapien eu, dignissim lacus. Vestibulum condimentum turpis ac ligula porttitor fringilla. Ut libero eros, egestas sed ex vel, viverra egestas augue. Phasellus lorem nisi, commodo id elementum aliquet, blandit ac leo. Quisque gravida, libero vel iaculis tempus, ligula nisi imperdiet velit, vel lobortis magna nibh sed mauris. Curabitur efficitur arcu sapien, non dapibus ipsum blandit commodo. Donec mollis dolor a augue lacinia, eget gravida sem placerat. Nullam ultrices in justo a pellentesque. Nam quis placerat ipsum. Integer convallis varius sapien, a ullamcorper metus sodales et. Aliquam erat volutpat. Praesent blandit, tellus sed consectetur gravida, nisi nisl interdum nulla, vel imperdiet lacus elit et elit. Nulla viverra tempus sapien, et eleifend justo vulputate id.",
  ],
  em: [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum magna libero, sit amet pharetra felis porttitor eu. Etiam et augue quis leo imperdiet varius nec ut dui. Fusce nec metus mi. In ac lobortis dui, eget fringilla elit. Fusce neque erat, posuere vel nulla ut, auctor ultricies purus. Aliquam placerat nec turpis non porttitor. In et ullamcorper sem. Ut vestibulum vestibulum neque, congue volutpat sapien. Ut condimentum sodales arcu, eget dignissim lorem efficitur eget. Phasellus aliquet velit nec lorem maximus elementum. Quisque sit amet orci massa.",
    "Nunc et elit varius, fermentum sapien eu, dignissim lacus. Vestibulum condimentum turpis ac ligula porttitor fringilla. Ut libero eros, egestas sed ex vel, viverra egestas augue. Phasellus lorem nisi, commodo id elementum aliquet, blandit ac leo. Quisque gravida, libero vel iaculis tempus, ligula nisi imperdiet velit, vel lobortis magna nibh sed mauris. Curabitur efficitur arcu sapien, non dapibus ipsum blandit commodo. Donec mollis dolor a augue lacinia, eget gravida sem placerat. Nullam ultrices in justo a pellentesque. Nam quis placerat ipsum. Integer convallis varius sapien, a ullamcorper metus sodales et. Aliquam erat volutpat. Praesent blandit, tellus sed consectetur gravida, nisi nisl interdum nulla, vel imperdiet lacus elit et elit. Nulla viverra tempus sapien, et eleifend justo vulputate id.",
  ],
  datel: [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum magna libero, sit amet pharetra felis porttitor eu. Etiam et augue quis leo imperdiet varius nec ut dui. Fusce nec metus mi. In ac lobortis dui, eget fringilla elit. Fusce neque erat, posuere vel nulla ut, auctor ultricies purus. Aliquam placerat nec turpis non porttitor. In et ullamcorper sem. Ut vestibulum vestibulum neque, congue volutpat sapien. Ut condimentum sodales arcu, eget dignissim lorem efficitur eget. Phasellus aliquet velit nec lorem maximus elementum. Quisque sit amet orci massa.",
    "Nunc et elit varius, fermentum sapien eu, dignissim lacus. Vestibulum condimentum turpis ac ligula porttitor fringilla. Ut libero eros, egestas sed ex vel, viverra egestas augue. Phasellus lorem nisi, commodo id elementum aliquet, blandit ac leo. Quisque gravida, libero vel iaculis tempus, ligula nisi imperdiet velit, vel lobortis magna nibh sed mauris. Curabitur efficitur arcu sapien, non dapibus ipsum blandit commodo. Donec mollis dolor a augue lacinia, eget gravida sem placerat. Nullam ultrices in justo a pellentesque. Nam quis placerat ipsum. Integer convallis varius sapien, a ullamcorper metus sodales et. Aliquam erat volutpat. Praesent blandit, tellus sed consectetur gravida, nisi nisl interdum nulla, vel imperdiet lacus elit et elit. Nulla viverra tempus sapien, et eleifend justo vulputate id.",
  ],
  ljmu: [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum magna libero, sit amet pharetra felis porttitor eu. Etiam et augue quis leo imperdiet varius nec ut dui. Fusce nec metus mi. In ac lobortis dui, eget fringilla elit. Fusce neque erat, posuere vel nulla ut, auctor ultricies purus. Aliquam placerat nec turpis non porttitor. In et ullamcorper sem. Ut vestibulum vestibulum neque, congue volutpat sapien. Ut condimentum sodales arcu, eget dignissim lorem efficitur eget. Phasellus aliquet velit nec lorem maximus elementum. Quisque sit amet orci massa.",
    "Nunc et elit varius, fermentum sapien eu, dignissim lacus. Vestibulum condimentum turpis ac ligula porttitor fringilla. Ut libero eros, egestas sed ex vel, viverra egestas augue. Phasellus lorem nisi, commodo id elementum aliquet, blandit ac leo. Quisque gravida, libero vel iaculis tempus, ligula nisi imperdiet velit, vel lobortis magna nibh sed mauris. Curabitur efficitur arcu sapien, non dapibus ipsum blandit commodo. Donec mollis dolor a augue lacinia, eget gravida sem placerat. Nullam ultrices in justo a pellentesque. Nam quis placerat ipsum. Integer convallis varius sapien, a ullamcorper metus sodales et. Aliquam erat volutpat. Praesent blandit, tellus sed consectetur gravida, nisi nisl interdum nulla, vel imperdiet lacus elit et elit. Nulla viverra tempus sapien, et eleifend justo vulputate id.",
  ],
  arch: [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum magna libero, sit amet pharetra felis porttitor eu. Etiam et augue quis leo imperdiet varius nec ut dui. Fusce nec metus mi. In ac lobortis dui, eget fringilla elit. Fusce neque erat, posuere vel nulla ut, auctor ultricies purus. Aliquam placerat nec turpis non porttitor. In et ullamcorper sem. Ut vestibulum vestibulum neque, congue volutpat sapien. Ut condimentum sodales arcu, eget dignissim lorem efficitur eget. Phasellus aliquet velit nec lorem maximus elementum. Quisque sit amet orci massa.",
    "Nunc et elit varius, fermentum sapien eu, dignissim lacus. Vestibulum condimentum turpis ac ligula porttitor fringilla. Ut libero eros, egestas sed ex vel, viverra egestas augue. Phasellus lorem nisi, commodo id elementum aliquet, blandit ac leo. Quisque gravida, libero vel iaculis tempus, ligula nisi imperdiet velit, vel lobortis magna nibh sed mauris. Curabitur efficitur arcu sapien, non dapibus ipsum blandit commodo. Donec mollis dolor a augue lacinia, eget gravida sem placerat. Nullam ultrices in justo a pellentesque. Nam quis placerat ipsum. Integer convallis varius sapien, a ullamcorper metus sodales et. Aliquam erat volutpat. Praesent blandit, tellus sed consectetur gravida, nisi nisl interdum nulla, vel imperdiet lacus elit et elit. Nulla viverra tempus sapien, et eleifend justo vulputate id.",
  ]
};


export default content;